name: Build and Deploy React app to azure DevOps
on:
  push:
    branches:
      - 25-migrate-frontend-code-id25

env:
  AZURE_WEBAPP_NAME: "middleware-hackai-frontend"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "Application"      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.13.1'                        # set this to the node version to use
  RESOURCEGROUPNAME: "middleware-hackai-frontend-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "middleware-hackai-frontend-plan"
  APPINSIGHTLOCATION: "South Central US"
  SKU: "S1 Standard"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install and build
      continue-on-error: true
      run: |
        cd Application
        npm install
        npm run build --if-present
    
    - name: Zip artifact for deployment
      run: zip release.zip ./* -qr

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: release.zip


  Deploy:
    name: Deploy to azure web app
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Downloading build artifact
    - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

    # Login to azure
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy web app on azure
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: release.zip